### ISSUE TITLE
check create friedman line

### ISSUE THREAD

**Issue by thompson318** [SciKit-Surgery/glenoidplanefitting#15]
Function createFriedmanLine doesn't return the midpoint for the third (z?) coordinate, check why this is?

**Comment by thompson318** [comment]
Is it because it's a 2D method?

**Comment by astaolaf** [comment]
> Is it because it's a 2D method?

When printing the point "pm" it should return a third coordinate. The z is defined as p1[2] which is the z of point 1. The z should be the same for all points since it is in 2D so using p1[2] should work.

**Comment by thompson318** [comment]
Thanks, I've added a check in the code to make sure that the z coordinates are the same.
